<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\avatar.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.4.1" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
	  <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
	  <ProjectReference Include="..\Repository\Repository.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\avatar.png" />
    <Resource Include="Images\back-image.jpg" />
    <Resource Include="Images\key-icon.png" />
    <Resource Include="Images\logo.png" />
    <Resource Include="Images\user-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Excels\" />
  </ItemGroup>

</Project>
